//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_firFilterAVX(SB), $0-40

    MOVQ result+0(FP), DI
    MOVQ input+8(FP), SI
    MOVQ taps+16(FP), DX
    MOVQ lengthTaps+24(FP), CX
    MOVQ length+32(FP), R8

    WORD $0x2941; BYTE $0xc8
	JE LBB0_6
    QUAD $0xc93145c08945e9d1
LBB0_2:
    LONG $0xc057f8c5; WORD $0xc985
	JE LBB0_5
    LONG $0x8941c031; BYTE $0xca
LBB0_4:
    QUAD $0x10fac5020c10fac5; QUAD $0xd20479e3c4040254
    QUAD $0xc420d12169e3c4e0; QUAD $0xfac53046142169e3
    LONG $0x0c465c10
    QUAD $0x1008465c2161e3c4     // vinsertps    xmm3, xmm3, dword [rsi + 2*rax + 8], 16
    QUAD $0x2004465c2161e3c4     // vinsertps    xmm3, xmm3, dword [rsi + 2*rax + 4], 32
    QUAD $0xe8c530c92161e3c4; QUAD $0x8348c158f8c5c959
    LONG $0x834108c0; WORD $0xffc2
	JNE LBB0_4
LBB0_5:
    QUAD $0x0479e3c4c816fac5; QUAD $0xa1c4ca58f2c5e7d0
    QUAD $0x0579e3c48f0c117a; QUAD $0xa1c4c158fac501c8
    QUAD $0xc18349048f44117a; QUAD $0xc1394d04c6834801
	JNE LBB0_2
LBB0_6:
    RET




TEXT ·_firFilterDecimateAVX(SB), $0-48

    MOVQ result+0(FP), DI
    MOVQ input+8(FP), SI
    MOVQ taps+16(FP), DX
    MOVQ decimate+24(FP), CX
    MOVQ lengthTaps+32(FP), R8
    MOVQ length+40(FP), R9

    WORD $0x2945; BYTE $0xc1
	JE LBB1_7
    QUAD $0x3145c98945e8d141
    LONG $0xd23145db
LBB1_2:
    WORD $0x8545; BYTE $0xc0
	JE LBB1_3
    QUAD $0xc586048d48d08944; QUAD $0xc58944db31c057f8
LBB1_5:
    QUAD $0x10fac51a0c10fac5; QUAD $0xd20479e3c4041a54
    QUAD $0xc420d12169e3c4e0; QUAD $0xfac53058142169e3
    LONG $0x0c585c10
    QUAD $0x1008585c2161e3c4     // vinsertps    xmm3, xmm3, dword [rax + 2*rbx + 8], 16
    QUAD $0x2004585c2161e3c4     // vinsertps    xmm3, xmm3, dword [rax + 2*rbx + 4], 32
    QUAD $0xe8c530c92161e3c4; QUAD $0x8348c158f8c5c959
    LONG $0xc58308c3; BYTE $0xff
	JNE LBB1_5
	JMP LBB1_6
LBB1_3:
    LONG $0xc057f8c5
LBB1_6:
    QUAD $0x0479e3c4c816fac5; QUAD $0xa1c4ca58f2c5e7d0
    QUAD $0x0579e3c49f0c117a; QUAD $0xa1c4c158fac501c8
    QUAD $0xca0141049f44117a
    LONG $0x01c38349; WORD $0x394d; BYTE $0xcb
	JNE LBB1_2
LBB1_7:
    RET
