//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_dotProductComplexComplexAVX(SB), $0-32

    MOVQ result+0(FP), DI
    MOVQ input+8(FP), SI
    MOVQ taps+16(FP), DX
    MOVQ length+24(FP), CX

    LONG $0xc057f8c5; WORD $0xe9c1; BYTE $0x04
	JE LBB0_3
    WORD $0xc031
LBB0_2:
    QUAD $0xfac50c024c10fac5; QUAD $0x025c10fac5021410
    QUAD $0xf0c500c9c6e0c504; QUAD $0x025c10fac5060c59
    QUAD $0xc4e0d20479e3c408
    LONG $0xd32169e3; BYTE $0x20
    QUAD $0x300806542169e3c4     // vinsertps    xmm2, xmm2, dword [rsi + rax + 8], 48
    QUAD $0xe3c404066410fac5
    LONG $0x06242159; BYTE $0x10
    QUAD $0x200c06642159e3c4     // vinsertps    xmm4, xmm4, dword [rsi + rax + 12], 32
    QUAD $0xe8c530db2159e3c4; QUAD $0xe8c5d958e8c5d359
    QUAD $0x0ac90c61e3c4c95c; QUAD $0x10c08348c158f8c5
    WORD $0xc183; BYTE $0xff
	JNE LBB0_2
LBB0_3:
    QUAD $0x0479e3c4c816fac5; QUAD $0xfac5ca58f2c5e7d0
    QUAD $0x01c80579e3c40f11; QUAD $0x4711fac5c158fac5
    BYTE $0x04
    RET
